# Generated by Django 5.0.4 on 2024-05-09 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_cart_created_cart_updated_product_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.FileField(default='users/empty_logo.png', upload_to='users/'),
        ),
    ]
